DROP TABLE IF EXISTS "InvoiceItem" CASCADE;
DROP TABLE IF EXISTS "Invoice" CASCADE;
DROP TABLE IF EXISTS "PaymentMethod" CASCADE;
DROP TABLE IF EXISTS "BillingInfo" CASCADE;
DROP TABLE IF EXISTS "Subscription" CASCADE;
DROP TABLE IF EXISTS "Plan" CASCADE;
DROP TABLE IF EXISTS "Message" CASCADE;
DROP TABLE IF EXISTS "Task" CASCADE;
DROP TABLE IF EXISTS "BoardColumn" CASCADE;
DROP TABLE IF EXISTS "Board" CASCADE;
DROP TABLE IF EXISTS "ProductImage" CASCADE;
DROP TABLE IF EXISTS "Product" CASCADE;

DROP TYPE IF EXISTS "InvoiceStatus";
DROP TYPE IF EXISTS "MessageStatus";
DROP TYPE IF EXISTS "TaskPriority";
DROP TYPE IF EXISTS "SubscriptionStatus";
