export enum NotificationEventType {
  REQUEST_CREATED = "REQUEST_CREATED",
  REQUEST_ASSIGNED = "REQUEST_ASSIGNED",
  REQUEST_STATUS_CHANGED = "REQUEST_STATUS_CHANGED",
  REQUEST_COMMENTED = "REQUEST_COMMENTED",
  REQUEST_MENTIONED = "REQUEST_MENTIONED",
  SLA_NEAR_BREACH_RESPONSE = "SLA_NEAR_BREACH_RESPONSE",
  SLA_NEAR_BREACH_RESOLUTION = "SLA_NEAR_BREACH_RESOLUTION"
}

export enum NotificationChannel {
  IN_APP = "IN_APP",
  EMAIL = "EMAIL"
}
